=== karl-lichileung/test/applist/WebContent/dpapplist.xsd
<?xml version="1.0"?>

<xsd:schema xmlns="dpapplist"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="dpapplist"
elementFormDefault="qualified">

<xsd:element name="AppList" type="DpAPP"/>
             
<xsd:complexType name="DpAPP">
  <xsd:sequence>
    <xsd:element name="dp_app" type="AppDetail" minOccurs="0" maxOccurs="unbounded"/>
  </xsd:sequence>
  <xsd:attribute name="type" type="TYPE" use="required"/>
  <xsd:attribute name="solution" type="SOLUTION" use="required"/>
  <xsd:attribute name="usedfor" type="USERFOR" use="required"/>
  <xsd:attribute name="fileversion" type="xsd:integer" use="optional"/>    
</xsd:complexType>
          
<xsd:simpleType name="TYPE">
   <xsd:restriction base="xsd:string">
       <xsd:enumeration value="integrationTest"/>     <!-- Integration Test  -->
       <xsd:enumeration value="preproduction"/>       <!-- Pre-Production    -->
       <xsd:enumeration value="production"/>          <!-- Production        -->
   </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="SOLUTION">
   <xsd:restriction base="xsd:string">
       <xsd:enumeration value="iChain22"/>   
       <xsd:enumeration value="iChain23"/>  
       <xsd:enumeration value="TAM41"/>
       <xsd:enumeration value="TAM51"/>   
       <xsd:enumeration value="SID6"/> 
       <xsd:enumeration value="WAC1"/>
       <xsd:enumeration value="WAC6"/>
       <xsd:enumeration value="NAM3"/>
       <xsd:enumeration value="FIM6"/>
       <xsd:enumeration value="any"/>         
   </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="USERFOR">
   <xsd:restriction base="xsd:string">
       <xsd:enumeration value="crossdomain"/>     <!-- Cross B/D Application List  -->
       <xsd:enumeration value="local"/>           <!-- Local B/D Application List  -->
   </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="VISUALFOR">
   <xsd:restriction base="xsd:string">
       <xsd:enumeration value="all"/>     <!-- no require condition  -->
       <xsd:enumeration value="condition"/>           <!-- yes require condition  -->
   </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="AppDetail">
  <xsd:sequence>
    <xsd:element name="dp_app_desc" minOccurs="1" >    
    	<xsd:simpleType>
    		<xsd:restriction base="xsd:string">
         		<xsd:minLength value="1"/>
        	</xsd:restriction>
    	</xsd:simpleType>
    </xsd:element>    
	<xsd:element name="dp_app_url" minOccurs="1">
    	<xsd:simpleType>
    		<xsd:restriction base="xsd:string">
         		<xsd:minLength value="1"/>
        	</xsd:restriction>
    	</xsd:simpleType>
	</xsd:element>		
	<xsd:element name="dp_domain_abbr" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="destination" type="xsd:string" minOccurs="0" maxOccurs="1"/>
	<xsd:element name="ap_protect_ext" type="xsd:string" minOccurs="0" maxOccurs="1"/>	
	<xsd:element name="dp_app_visualfor" type="VISUALFOR" minOccurs="1"/> 
	<xsd:element name="dp_app_condition" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
  </xsd:sequence>
</xsd:complexType>              

</xsd:schema>

=== karl-lichileung/test/applist/WebContent/lapplist.xml
<?xml version="1.0"?>
<AppList xmlns="dpapplist"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="dpapplist dpapplist.xsd" type="integrationTest" usedfor="local" solution="any">
	<dp_app>
		<dp_app_desc>Test local Application SP1</dp_app_desc>
		<dp_app_url>https://sp.test.org/sp1</dp_app_url>
		<dp_domain_abbr>LOCAL1</dp_domain_abbr>
		<dp_app_visualfor>all</dp_app_visualfor>	
	</dp_app>
	<dp_app>
		<dp_app_desc>Test local Application SP2</dp_app_desc>
		<dp_app_url>https://sp.test.org/sp2</dp_app_url>
		<dp_domain_abbr>LOCAL2</dp_domain_abbr>
		<dp_app_visualfor>all</dp_app_visualfor>	
	</dp_app>
	<!-- For example if you want to add a new application called Application 1,
	the application url is http://dp.novellit.hksarg/itapp/app1/app1.jsp,
	and the application no need to check any attribute from the user profile.

	e.g.
	<dp_app>
		<dp_app_desc>Application 1</dp_app_desc>
		<dp_app_url>/itapp/app1/app1.jsp</dp_app_url>
		<dp_app_visualfor>all</dp_app_visualfor>
	</dp_app>

	-->

	<!-- For example if you want to add a new application called Application 2,
	the application url is http://dp.novellit.hksarg/itapp/app2/app2.jsp,
	and the application need to check the deptment id attribute from the user profile.
	for details of attribute please refer to the ldschema.xml or lldschema.xml
	e.g.
	<dp_app>
		<dp_app_desc>Applicatio2</dp_app_desc>
		<dp_app_url>/itapp/app2/app2.jsp</dp_app_url>
		<dp_app_visualfor>condition</dp_app_visualfor>
		<dp_app_condition>DPDEPTID equal "ibmit"</dp_app_condition>
	</dp_app>
	<dp_app>
		<dp_app_desc>OSDP App3 (Conditional)</dp_app_desc>
		<dp_app_url>/itapp/app3/app3.jsp</dp_app_url>
		<dp_app_visualfor>condition</dp_app_visualfor>
		<dp_app_condition>DPRANKCODE equal "99"</dp_app_condition>
	</dp_app>
	<dp_app>
		<dp_app_desc>OSDP App4 (Conditional AND)</dp_app_desc>
		<dp_app_url>/itapp/app4/app4.jsp</dp_app_url>
		<dp_app_visualfor>condition</dp_app_visualfor>
		<dp_app_condition>DPRANKCODE equal "99" AND DPHKID equal "11111"</dp_app_condition>
	</dp_app>
	<dp_app>
		<dp_app_desc>OSDP App5 (Conditional OR)</dp_app_desc>
		<dp_app_url>/itapp/app5/app5.jsp</dp_app_url>
		<dp_app_visualfor>condition</dp_app_visualfor>
		<dp_app_condition>DPRANKCODE equal "99"</dp_app_condition>
		<dp_app_condition>DPSTAFFGROUP equal "2222"</dp_app_condition>
	</dp_app>
	-->
</AppList>

=== karl-lichileung/test/applist/WebContent/applist.xml
<?xml version="1.0"?>
<AppList xmlns="dpapplist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="dpapplist dpapplist.xsd" type="production" solution="any" usedfor="crossdomain" fileversion="9">
<dp_app>
<dp_app_desc>Test Application 1</dp_app_desc>
<dp_app_url>https://sp1.test.ccgo.org/app1</dp_app_url>
<dp_domain_abbr>REMOTE1</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>all</dp_app_visualfor>
</dp_app>
<dp_app>
<dp_app_desc>Test Application 2</dp_app_desc>
<dp_app_url>https://dp.ibmit.ccgo.hksarg/itapp/app2/app2.jsp</dp_app_url>
<dp_domain_abbr>afcd</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPHKID equal "11121" AND cn equal "user"</dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>Test Application 3</dp_app_desc>
<dp_app_url>https://app2</dp_app_url>
<dp_domain_abbr>hkpo</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPHKID equal "11121" AND cn equal "user"</dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>Demo 1 (rank = 30)</dp_app_desc>
<dp_app_url>https://rank30.com</dp_app_url>
<dp_domain_abbr>hkpo</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPRANKCODE equal "30"</dp_app_condition>
<dp_app_condition>EMPLOYEETYPE equal "99"</dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>For every user no condition set</dp_app_desc>
<dp_app_url>https://everyuser.com</dp_app_url>
<dp_domain_abbr>hkpo</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPRANKCODE equal "30"</dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>App1_Cond_saml_1</dp_app_desc>
<dp_app_url>https://dp.nam32it.ccgo.hksarg/itapp/app1/app1.jsp</dp_app_url>
<dp_domain_abbr>NAM32IT</dp_domain_abbr>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPDEPTID equal "OSDP"<saml>1.1</saml></dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>CSP Eprocurement(agent)</dp_app_desc>
<dp_app_url>https://sso.csp.ccgo.hksarg</dp_app_url>
<dp_domain_abbr>CSP</dp_domain_abbr>
<destination>eprocurement</destination>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>condition</dp_app_visualfor>
<dp_app_condition>DPDEPTID equal "OSDP"<saml>2.0</saml></dp_app_condition>
</dp_app>
<dp_app>
<dp_app_desc>CSP GOVHRMS CENTRAL(Fedlet)</dp_app_desc>
<dp_app_url>https://sso.csp.ccgo.hksarg</dp_app_url>
<dp_domain_abbr>CSP</dp_domain_abbr>
<destination>GOVHRMS_CENTRAL</destination>
<ap_protect_ext>false</ap_protect_ext>
<dp_app_visualfor>all</dp_app_visualfor>
</dp_app>
</AppList>
