=== karl-lichileung/test/applist/WebContent/dpuser.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="dpuser"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="dpuser"
elementFormDefault="qualified">

 	 <xsd:element name="dp_ldap_schema" type="dpldapType"/>

     <xsd:complexType name="dpldapType">
     	<xsd:choice minOccurs="0" maxOccurs="unbounded">
         	<xsd:element name="attribute_name" type="valueType"/>
        </xsd:choice> 	
     </xsd:complexType>

     
<xsd:complexType name="valueType">
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="vtype" type="atype"/>		
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

     <xsd:simpleType name="atype">
          <xsd:restriction base="xsd:string">
                <xsd:enumeration value="cis"/>         <!-- case insensitive string  -->
                <xsd:enumeration value="css"/>         <!-- case sensitive string  -->
                <xsd:enumeration value="int"/>         <!-- integer  -->
                <xsd:enumeration value="dec"/>         <!-- decimal  -->
          </xsd:restriction>
     </xsd:simpleType>   

            
</xsd:schema>

=== karl-lichileung/test/applist/WebContent/ldschema.xml
<?xml version="1.0"?>
<dp_ldap_schema xmlns="dpuser"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="dpuser dpuser.xsd">
	<attribute_name vtype="cis">uid</attribute_name>
	<attribute_name vtype="cis">sn</attribute_name>
	<attribute_name vtype="cis">employeeType</attribute_name>
	<attribute_name vtype="cis">cn</attribute_name>
	<attribute_name vtype="cis">DPHKID</attribute_name>
	<attribute_name vtype="cis">DPDEPTID</attribute_name>
	<attribute_name vtype="cis">DPRANKCODE</attribute_name>
	<attribute_name vtype="int">DPSTAFFGROUP</attribute_name>
</dp_ldap_schema>
